In [3]:
import pandas as pd

# Load the dataset
# Skip the first few rows based on the preview
df = pd.read_excel('/content/drive/MyDrive/Matlab Project/Co2 solubility.xlsx', skiprows=3)

# Display basic info and the first few rows
print("--- Data Info ---")
print(df.info())
print("\n--- First 5 Rows ---")
print(df.head())
print("\n--- Value Counts for first column (to check header alignment) ---")
print(df.iloc[:, 0].value_counts().head())

--- Data Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9112 entries, 0 to 9111
Data columns (total 16 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   IL-CO2 Systems                   8868 non-null   object
 1   Cation                           8868 non-null   object
 2   Anion                            8868 non-null   object
 3   T /K                             8868 non-null   float64
 4   P /bar                           8868 non-null   float64
 5   Solubility (ref.)                8868 non-null   float64
 6   Fugacity /bar                    8868 non-null   float64
 7   Solubility(cal.)                 9013 non-null   object
 8   RD1                              9013 non-null   object
 9   Solubility(COSMO-RS(combi2005))  9112 non-null   object
 10  RD1.1                            9112 non-null   float64
 11  Solubility(COSMO-RS(combi1998))  9112 non-null   object
 12  RD2                              9112 non-null   float64
 13  Experimental Method              8868 non-null   object
 14  No. of refs.                     8868 non-null   object
 15  Full References                  8868 non-null   object
dtypes: float64(6), object(10)
memory usage: 1.1+ MB
None

--- First 5 Rows ---
         IL-CO2 Systems      Cation   Anion    T /K  P /bar  \
0  [(ETO)2IM][Tf2N]-CO2  [(ETO)2IM]  [Tf2N]  303.65    21.5
1  [(ETO)2IM][Tf2N]-CO2  [(ETO)2IM]  [Tf2N]  313.35    25.7
2  [(ETO)2IM][Tf2N]-CO2  [(ETO)2IM]  [Tf2N]  324.15    31.2
3  [(ETO)2IM][Tf2N]-CO2  [(ETO)2IM]  [Tf2N]  333.85    36.0
4  [(ETO)2IM][Tf2N]-CO2  [(ETO)2IM]  [Tf2N]  343.65    41.1

   Solubility (ref.)  Fugacity /bar Solubility(cal.) RD1  \
0              0.396      19.372683                -   -
1              0.396      22.970289                -   -
2              0.396      27.622487                -   -
3              0.396      31.703425                -   -
4              0.396      36.044576                -   -

  Solubility(COSMO-RS(combi2005))     RD1.1 Solubility(COSMO-RS(combi1998))  \
0                        0.287634  0.273651                        0.290442
1                        0.279902  0.293176                          0.2823
2                        0.272465  0.311957                        0.274455
3                        0.261359  0.340003                        0.262992
4                        0.249712  0.369415                        0.251019

        RD2              Experimental Method No. of refs.  \
0  0.266562  Synthetic (Bubble Point) Method        [189]
1  0.287122  Synthetic (Bubble Point) Method        [189]
2  0.306932  Synthetic (Bubble Point) Method        [189]
3  0.335878  Synthetic (Bubble Point) Method        [189]
4  0.366113  Synthetic (Bubble Point) Method        [189]

                                     Full References
0  Anne-Laure Revelli, Fabrice Mutelet, Jean-Noël...
1  Anne-Laure Revelli, Fabrice Mutelet, Jean-Noël...
2  Anne-Laure Revelli, Fabrice Mutelet, Jean-Noël...
3  Anne-Laure Revelli, Fabrice Mutelet, Jean-Noël...
4  Anne-Laure Revelli, Fabrice Mutelet, Jean-Noël...

--- Value Counts for first column (to check header alignment) ---
IL-CO2 Systems
[BMIM][PF6]-CO2     719
[HMIM][Tf2N]-CO2    527
[EMIM][Tf2N]-CO2    526
[BMIM][Tf2N]-CO2    525
[BMIM][BF4]-CO2     457
Name: count, dtype: int64

In [6]:
import numpy as np

# 1. Remove rows where IL-CO2 Systems is NaN
df_cleaned = df.dropna(subset=['IL-CO2 Systems']).copy()

# 2. Replace '-' with NaN across the whole dataframe
df_cleaned.replace('-', np.nan, inplace=True)

# 3. Convert relevant columns to numeric
cols_to_fix = [
    'Solubility(cal.)', 'RD1', 'Solubility(COSMO-RS(combi2005))',
    'RD1.1', 'Solubility(COSMO-RS(combi1998))', 'RD2'
]
for col in cols_to_fix:
    df_cleaned[col] = pd.to_numeric(df_cleaned[col], errors='coerce')

# 4. Check for and drop duplicates
duplicates_count = df_cleaned.duplicated().sum()
df_cleaned.drop_duplicates(inplace=True)

# 5. Drop purely descriptive columns
df_cleaned.drop(columns=['Full References', 'No. of refs.'], inplace=True)

# Inspect missing values after conversion
print("--- Missing Values Count ---")
print(df_cleaned.isnull().sum())

# Inspect column names to ensure everything is clean
print("\n--- Column Names ---")
print(df_cleaned.columns.tolist())

--- Missing Values Count ---
IL-CO2 Systems                        0
Cation                                0
Anion                                 0
T /K                                  0
P /bar                                0
Solubility (ref.)                     0
Fugacity /bar                         0
Solubility(cal.)                   2800
RD1                                2800
Solubility(COSMO-RS(combi2005))       0
RD1.1                                 0
Solubility(COSMO-RS(combi1998))       0
RD2                                   0
Experimental Method                   0
dtype: int64

--- Column Names ---
['IL-CO2 Systems', 'Cation', 'Anion', 'T /K', 'P /bar', 'Solubility (ref.)', 'Fugacity /bar', 'Solubility(cal.)', 'RD1', 'Solubility(COSMO-RS(combi2005))', 'RD1.1', 'Solubility(COSMO-RS(combi1998))', 'RD2', 'Experimental Method']

/tmp/ipykernel_3846/150731632.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_cleaned.replace('-', np.nan, inplace=True)

,IL-CO2 Systems,Cation,Anion,T /K,P /bar,Solubility (ref.),Fugacity /bar,Solubility(cal.),RD1,Solubility(COSMO-RS(combi2005)),RD1.1,Solubility(COSMO-RS(combi1998)),RD2,Experimental Method
0,[(ETO)2IM][Tf2N]-CO2,[(ETO)2IM],[Tf2N],303.65,21.5,0.396,19.372683,NaN,NaN,0.287634,0.273651,0.290442,0.266562,Synthetic (Bubble Point) Method
1,[(ETO)2IM][Tf2N]-CO2,[(ETO)2IM],[Tf2N],313.35,25.7,0.396,22.970289,NaN,NaN,0.279902,0.293176,0.282300,0.287122,Synthetic (Bubble Point) Method
2,[(ETO)2IM][Tf2N]-CO2,[(ETO)2IM],[Tf2N],324.15,31.2,0.396,27.622487,NaN,NaN,0.272465,0.311957,0.274455,0.306932,Synthetic (Bubble Point) Method
3,[(ETO)2IM][Tf2N]-CO2,[(ETO)2IM],[Tf2N],333.85,36.0,0.396,31.703425,NaN,NaN,0.261359,0.340003,0.262992,0.335878,Synthetic (Bubble Point) Method
4,[(ETO)2IM][Tf2N]-CO2,[(ETO)2IM],[Tf2N],343.65,41.1,0.396,36.044576,NaN,NaN,0.249712,0.369415,0.251019,0.366113,Synthetic (Bubble Point) Method

In [7]:
cleaned_co2_solubility = df_cleaned
cleaned_co2_solubility.head()

,IL-CO2 Systems,Cation,Anion,T /K,P /bar,Solubility (ref.),Fugacity /bar,Solubility(cal.),RD1,Solubility(COSMO-RS(combi2005)),RD1.1,Solubility(COSMO-RS(combi1998)),RD2,Experimental Method
0,[(ETO)2IM][Tf2N]-CO2,[(ETO)2IM],[Tf2N],303.65,21.5,0.396,19.372683,NaN,NaN,0.287634,0.273651,0.290442,0.266562,Synthetic (Bubble Point) Method
1,[(ETO)2IM][Tf2N]-CO2,[(ETO)2IM],[Tf2N],313.35,25.7,0.396,22.970289,NaN,NaN,0.279902,0.293176,0.282300,0.287122,Synthetic (Bubble Point) Method
2,[(ETO)2IM][Tf2N]-CO2,[(ETO)2IM],[Tf2N],324.15,31.2,0.396,27.622487,NaN,NaN,0.272465,0.311957,0.274455,0.306932,Synthetic (Bubble Point) Method
3,[(ETO)2IM][Tf2N]-CO2,[(ETO)2IM],[Tf2N],333.85,36.0,0.396,31.703425,NaN,NaN,0.261359,0.340003,0.262992,0.335878,Synthetic (Bubble Point) Method
4,[(ETO)2IM][Tf2N]-CO2,[(ETO)2IM],[Tf2N],343.65,41.1,0.396,36.044576,NaN,NaN,0.249712,0.369415,0.251019,0.366113,Synthetic (Bubble Point) Method

In [8]:
print("--- Data Info ---")
print(df_cleaned.info())
print("\n--- First 5 Rows ---")
print(df_cleaned.head())
print("\n--- Value Counts for first column (to check header alignment) ---")
print(df_cleaned.iloc[:, 0].value_counts().head())

--- Data Info ---
<class 'pandas.core.frame.DataFrame'>
Index: 8803 entries, 0 to 9110
Data columns (total 14 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   IL-CO2 Systems                   8803 non-null   object
 1   Cation                           8803 non-null   object
 2   Anion                            8803 non-null   object
 3   T /K                             8803 non-null   float64
 4   P /bar                           8803 non-null   float64
 5   Solubility (ref.)                8803 non-null   float64
 6   Fugacity /bar                    8803 non-null   float64
 7   Solubility(cal.)                 6003 non-null   float64
 8   RD1                              6003 non-null   float64
 9   Solubility(COSMO-RS(combi2005))  8803 non-null   float64
 10  RD1.1                            8803 non-null   float64
 11  Solubility(COSMO-RS(combi1998))  8803 non-null   float64
 12  RD2                              8803 non-null   float64
 13  Experimental Method              8803 non-null   object
dtypes: float64(10), object(4)
memory usage: 1.0+ MB
None

--- First 5 Rows ---
         IL-CO2 Systems      Cation   Anion    T /K  P /bar  \
0  [(ETO)2IM][Tf2N]-CO2  [(ETO)2IM]  [Tf2N]  303.65    21.5
1  [(ETO)2IM][Tf2N]-CO2  [(ETO)2IM]  [Tf2N]  313.35    25.7
2  [(ETO)2IM][Tf2N]-CO2  [(ETO)2IM]  [Tf2N]  324.15    31.2
3  [(ETO)2IM][Tf2N]-CO2  [(ETO)2IM]  [Tf2N]  333.85    36.0
4  [(ETO)2IM][Tf2N]-CO2  [(ETO)2IM]  [Tf2N]  343.65    41.1

   Solubility (ref.)  Fugacity /bar  Solubility(cal.)  RD1  \
0              0.396      19.372683               NaN  NaN
1              0.396      22.970289               NaN  NaN
2              0.396      27.622487               NaN  NaN
3              0.396      31.703425               NaN  NaN
4              0.396      36.044576               NaN  NaN

   Solubility(COSMO-RS(combi2005))     RD1.1  Solubility(COSMO-RS(combi1998))  \
0                         0.287634  0.273651                         0.290442
1                         0.279902  0.293176                         0.282300
2                         0.272465  0.311957                         0.274455
3                         0.261359  0.340003                         0.262992
4                         0.249712  0.369415                         0.251019

        RD2              Experimental Method
0  0.266562  Synthetic (Bubble Point) Method
1  0.287122  Synthetic (Bubble Point) Method
2  0.306932  Synthetic (Bubble Point) Method
3  0.335878  Synthetic (Bubble Point) Method
4  0.366113  Synthetic (Bubble Point) Method

--- Value Counts for first column (to check header alignment) ---
IL-CO2 Systems
[BMIM][PF6]-CO2     697
[EMIM][Tf2N]-CO2    524
[HMIM][Tf2N]-CO2    523
[BMIM][Tf2N]-CO2    515
[BMIM][BF4]-CO2     452
Name: count, dtype: int64

In [9]:
!pip install rdkit

Collecting rdkit
  Downloading rdkit-2026.3.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rdkit) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from rdkit) (11.3.0)
Downloading rdkit-2026.3.1-cp312-cp312-manylinux_2_28_x86_64.whl (37.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.0/37.0 MB 39.6 MB/s eta 0:00:00
Installing collected packages: rdkit
Successfully installed rdkit-2026.3.1

In [12]:
from rdkit import Chem
from rdkit.Chem import Descriptors

# 1. Comprehensive Mapping Dictionary
cation_smiles = {
    '[(ETO)2IM]': 'CCOn1cc[n+](OCC)c1', '[b2-Nic]': 'CCCCOC(=O)c1ccc[n+](c1)CCCC', '[BBIM]': 'CCCCn1cc[n+](c1)CCCC',
    '[bhea]': 'OCC[NH2+]CCO', '[BMIM]': 'CCCCn1cc[n+](c1)C', '[BMPYR]': 'CCCC[N+]1(C)CCCC1', '[BPY]': 'CCCC[n+]1ccccc1',
    '[C2OMIM]': 'COCCn1cc[n+](c1)C', '[C3MPYR]': 'CCC[N+]1(C)CCCC1', '[C5MIM]': 'CCCCCn1cc[n+](c1)C', '[C5MPYR]': 'CCCCC[N+]1(C)CCCC1',
    '[C6F9MIM]': 'FC(F)(F)C(F)(F)C(F)(F)CCn1cc[n+](c1)C', '[C7MPYR]': 'CCCCCCC[N+]1(C)CCCC1', '[C8F13MIM]': 'FC(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)CCn1cc[n+](c1)C',
    '[DMFH]': 'CN(C)C=[NH2+]', '[DMIM]': 'Cn1cc[n+](c1)C', '[EMIM]': 'CCn1cc[n+](c1)C', '[Et3NBH2MIM]': 'CC[N+](CC)(CC)CCCP(=O)(O)O',
    '[ETT]': 'CC[P+](c1ccccc1)(c2ccccc2)c3ccccc3', '[he]': '[NH3+]CCO', '[hea]': '[NH3+]CCO', '[HEMIM]': 'OCCn1cc[n+](c1)C',
    '[hheme]': 'OCCn1c(C)c[n+](c1)C', '[HMIM]': 'CCCCCCn1cc[n+](c1)C', '[HMMIM]': 'CCCCCCn1c(C)c[n+](c1)C', '[HMPY]': 'CCCCCC[n+]1ccc(C)cc1',
    '[HMPYR]': 'CCCCCC[N+]1(C)CCCC1', '[HOC3MIM]': 'OCCCn1cc[n+](c1)C', '[m-2-HEA]': 'C[NH2+]CCO', '[MDEA]': 'C[NH+](CCO)CCO',
    '[MMIM]': 'Cn1cc[n+](c1)C', '[N1,1,1,2-OH]': 'C[N+](C)(C)CCO', '[N1,1,3,2-OH]': 'C[N+](C)(C)CC(C)O', '[N1,8,8,8]': 'C[N+](CCCCCCCC)(CCCCCCCC)CCCCCCCC',
    '[N2,1,1,3]': 'CC[N+](C)(C)CCC', '[N4,1,1,1]': 'CCCC[N+](C)(C)C', '[N1,4,4,4]': 'C[N+](CCCC)(CCCC)CCCC', '[N4,4,4,4]': 'CCCC[N+](CCCC)(CCCC)CCCC',
    '[NMIM]': 'c1c[nH]c[n+]1C', '[NMPYR]': 'C[N+]1CCCC1', '[OMIM]': 'CCCCCCCCn1cc[n+](c1)C', '[OMPYR]': 'CCCCCCCC[N+]1(C)CCCC1',
    '[P1,4,4,4]': 'C[P+](CCCC)(CCCC)CCCC', '[P4,4,4,4]': 'CCCC[P+](CCCC)(CCCC)CCCC', '[P6,6,6,14]': 'CCCCCC[P+](CCCCCC)(CCCCCC)CCCCCCCCCCCCCC',
    '[Py2OH]': 'OCC[n+]1ccccc1', '[thea]': 'OCC[NH+](CCO)CCO', '[TMG]': 'CN(C)C(=[NH2+])N(C)C'
}

anion_smiles = {
    '[Tf2N]': 'C(F)(F)(F)S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F', '[MeSO3]': 'CS(=O)(=O)[O-]', '[Ac]': 'CC(=O)[O-]', '[L]': 'CC(O)C(=O)[O-]',
    '[BF4]': 'F[B-](F)(F)F', '[C3F7CO2]': 'FC(F)(F)C(F)(F)C(F)(F)C(=O)[O-]', '[C7F15CO2]': 'FC(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)C(=O)[O-]',
    '[Cl]': '[Cl-]', '[DBPO4]': 'CCCCOP(=O)([O-])OCCCC', '[DCA]': 'N#C[N-]C#N', '[eFAP]': 'F[P-](F)(F)(C(F)(F)C(F)(F)F)(C(F)(F)C(F)(F)F)C(F)(F)C(F)(F)F',
    '[IAAc]': 'IC[C](=O)[O-]', '[ISB]': 'C1C(OC2C1OC(C(O2)O)O)[O-]', '[LEV]': 'CC(=O)CCC(=O)[O-]', '[MDEGSO4]': 'COCCOCCS(=O)(=O)[O-]',
    '[MeSO4]': 'COS(=O)(=O)[O-]', '[methide]': 'C(S(=O)(=O)C(F)(F)F)(S(=O)(=O)C(F)(F)F)[S-](=O)(=O)C(F)(F)F', '[NO3]': '[O-][N+](=O)[O-]',
    '[PF6]': 'F[P-](F)(F)(F)(F)F', '[Pro]': 'C1CCNC1C(=O)[O-]', '[SCN]': '[S-]C#N', '[SUC]': '[O-]C(=O)CCC(=O)[O-]', '[TFA]': 'FC(F)(F)C(=O)[O-]',
    '[TFES]': 'FC(F)C(F)(F)S(=O)(=O)[O-]', '[TfO]': 'FC(F)(F)S(=O)(=O)[O-]', '[TMA]': 'O=C([O-])c1cc(cc(c1)C(=O)[O-])C(=O)[O-]',
    '[IDA]': '[O-]C(=O)CNCC(=O)[O-]', '[bFAP]': 'F[P-](F)(F)(C(F)(F)C(F)(F)C(F)(F)C(F)(F)F)(C(F)(F)C(F)(F)C(F)(F)C(F)(F)F)C(F)(F)C(F)(F)C(F)(F)C(F)(F)F',
    '[DEPO4]': 'CCOP(=O)([O-])OCC', '[EtSO4]': 'CCOS(=O)(=O)[O-]', '[FOR]': '[H]C(=O)[O-]', '[ACE]': 'CC1=CC(=O)[N-]S(=O)(=O)O1',
    '[Br]': '[Br-]', '[pFAP]': 'F[P-](F)(F)(C(F)(F)C(F)(F)F)(C(F)(F)C(F)(F)F)C(F)(F)C(F)(F)F', '[SAC]': 'C1=CC=C2C(=C1)C(=O)[N-]S2(=O)=O',
    '[TCB]': '[B-](C#N)(C#N)(C#N)C#N', '[DMPO4]': 'COP(=O)([O-])OC', '[MP]': 'CP(=O)([O-])O', '[doc]': 'CCCCC(CC)COC(=O)CC(C(=O)OCC(CC)CCCC)S(=O)(=O)[O-]',
    '[TOS]': 'Cc1ccc(cc1)S(=O)(=O)[O-]', '[Ala]': 'CC(N)C(=O)[O-]', '[C12H25PhSO3]': 'CCCCCCCCCCCCc1ccc(cc1)S(=O)(=O)[O-]',
    '[Gly]': 'NCC(=O)[O-]', '[Ile]': 'CCC(C)C(N)C(=O)[O-]', '[Lys]': 'NCCCCC(N)C(=O)[O-]', '[phos]': '[O-]P(=O)([O-])[O-]',
    '[Sar]': 'CNCC(=O)[O-]', '[Tau]': 'NCCS(=O)(=O)[O-]'
}

def smiles_to_mol(smiles):
    """Safely convert SMILES to RDKit Mol"""
    if pd.isna(smiles):
        return None
    try:
        return Chem.MolFromSmiles(smiles)
    except:
        return None

def compute_descriptors(mol):
    """Return descriptor dict safely"""
    if mol is None:
        return {
            "MW": None,
            "LogP": None,
            "TPSA": None
        }
    return {
        "MW": Descriptors.MolWt(mol),
        "LogP": Descriptors.MolLogP(mol),
        "TPSA": Descriptors.TPSA(mol)
    }

def add_rdkit_features(df_cleaned, cation_smiles, anion_smiles):
    # --- Map SMILES ---
    df_cleaned['cat_smiles'] = df_cleaned['Cation'].map(cation_smiles)
    df_cleaned['ani_smiles'] = df_cleaned['Anion'].map(anion_smiles)

    # --- Convert to molecules ONCE ---
    df_cleaned['cat_mol'] = df_cleaned['cat_smiles'].apply(smiles_to_mol)
    df_cleaned['ani_mol'] = df_cleaned['ani_smiles'].apply(smiles_to_mol)

    # --- Compute descriptors ---
    cat_desc = df_cleaned['cat_mol'].apply(compute_descriptors).apply(pd.Series)
    ani_desc = df_cleaned['ani_mol'].apply(compute_descriptors).apply(pd.Series)

    # --- Rename columns ---
    cat_desc = cat_desc.add_prefix('cat_')
    ani_desc = ani_desc.add_prefix('ani_')

    # --- Merge back ---
    df_cleaned = pd.concat([df_cleaned, cat_desc, ani_desc], axis=1)

    # --- Optional: drop intermediate mol objects ---
    df_cleaned.drop(columns=['cat_mol', 'ani_mol'], inplace=True)

    return df_cleaned


# Apply and Save
df_enriched = add_rdkit_features(df_cleaned, cation_smiles, anion_smiles)

[15:52:41] Explicit valence for atom # 15 S, 6, is greater than permitted
[15:52:41] Explicit valence for atom # 15 S, 6, is greater than permitted
[15:52:41] Explicit valence for atom # 15 S, 6, is greater than permitted
[15:52:41] Explicit valence for atom # 15 S, 6, is greater than permitted
[15:52:41] Explicit valence for atom # 15 S, 6, is greater than permitted
[15:52:41] Explicit valence for atom # 15 S, 6, is greater than permitted
[15:52:41] Explicit valence for atom # 15 S, 6, is greater than permitted
[15:52:41] Explicit valence for atom # 15 S, 6, is greater than permitted
[15:52:41] Explicit valence for atom # 15 S, 6, is greater than permitted
[15:52:41] Explicit valence for atom # 15 S, 6, is greater than permitted
[15:52:41] Explicit valence for atom # 15 S, 6, is greater than permitted
[15:52:41] Explicit valence for atom # 15 S, 6, is greater than permitted
[15:52:41] Explicit valence for atom # 15 S, 6, is greater than permitted
[15:52:41] Explicit valence for atom # 15 S, 6, is greater than permitted
[15:52:41] Explicit valence for atom # 15 S, 6, is greater than permitted
[15:52:41] Explicit valence for atom # 15 S, 6, is greater than permitted
[15:52:41] Explicit valence for atom # 15 S, 6, is greater than permitted
[15:52:41] Explicit valence for atom # 15 S, 6, is greater than permitted
[15:52:41] Explicit valence for atom # 15 S, 6, is greater than permitted
[15:52:41] Explicit valence for atom # 15 S, 6, is greater than permitted
[15:52:41] Explicit valence for atom # 15 S, 6, is greater than permitted

In [13]:
df_enriched.head()

,IL-CO2 Systems,Cation,Anion,T /K,P /bar,Solubility (ref.),Fugacity /bar,Solubility(cal.),RD1,Solubility(COSMO-RS(combi2005)),...,RD2,Experimental Method,cat_smiles,ani_smiles,cat_MW,cat_LogP,cat_TPSA,ani_MW,ani_LogP,ani_TPSA
0,[(ETO)2IM][Tf2N]-CO2,[(ETO)2IM],[Tf2N],303.65,21.5,0.396,19.372683,NaN,NaN,0.287634,...,0.266562,Synthetic (Bubble Point) Method,CCOn1cc[n+](OCC)c1,C(F)(F)(F)S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F,157.193,-0.3274,27.27,280.147,1.0593,82.38
1,[(ETO)2IM][Tf2N]-CO2,[(ETO)2IM],[Tf2N],313.35,25.7,0.396,22.970289,NaN,NaN,0.279902,...,0.287122,Synthetic (Bubble Point) Method,CCOn1cc[n+](OCC)c1,C(F)(F)(F)S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F,157.193,-0.3274,27.27,280.147,1.0593,82.38
2,[(ETO)2IM][Tf2N]-CO2,[(ETO)2IM],[Tf2N],324.15,31.2,0.396,27.622487,NaN,NaN,0.272465,...,0.306932,Synthetic (Bubble Point) Method,CCOn1cc[n+](OCC)c1,C(F)(F)(F)S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F,157.193,-0.3274,27.27,280.147,1.0593,82.38
3,[(ETO)2IM][Tf2N]-CO2,[(ETO)2IM],[Tf2N],333.85,36.0,0.396,31.703425,NaN,NaN,0.261359,...,0.335878,Synthetic (Bubble Point) Method,CCOn1cc[n+](OCC)c1,C(F)(F)(F)S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F,157.193,-0.3274,27.27,280.147,1.0593,82.38
4,[(ETO)2IM][Tf2N]-CO2,[(ETO)2IM],[Tf2N],343.65,41.1,0.396,36.044576,NaN,NaN,0.249712,...,0.366113,Synthetic (Bubble Point) Method,CCOn1cc[n+](OCC)c1,C(F)(F)(F)S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F,157.193,-0.3274,27.27,280.147,1.0593,82.38

In [14]:
df_enriched.columns

Index(['IL-CO2 Systems', 'Cation', 'Anion', 'T /K', 'P /bar',
       'Solubility (ref.)', 'Fugacity /bar', 'Solubility(cal.)', 'RD1',
       'Solubility(COSMO-RS(combi2005))', 'RD1.1',
       'Solubility(COSMO-RS(combi1998))', 'RD2', 'Experimental Method',
       'cat_smiles', 'ani_smiles', 'cat_MW', 'cat_LogP', 'cat_TPSA', 'ani_MW',
       'ani_LogP', 'ani_TPSA'],
      dtype='object')

In [17]:
CO2_solubility_dataset = df_enriched.copy()
CO2_solubility_dataset = CO2_solubility_dataset.drop(columns=['Cation', 'Anion', 'Solubility(cal.)', 'RD1',
       'Solubility(COSMO-RS(combi2005))', 'RD1.1',
       'Solubility(COSMO-RS(combi1998))', 'RD2' ])
CO2_solubility_dataset.head()

,IL-CO2 Systems,T /K,P /bar,Solubility (ref.),Fugacity /bar,Experimental Method,cat_smiles,ani_smiles,cat_MW,cat_LogP,cat_TPSA,ani_MW,ani_LogP,ani_TPSA
0,[(ETO)2IM][Tf2N]-CO2,303.65,21.5,0.396,19.372683,Synthetic (Bubble Point) Method,CCOn1cc[n+](OCC)c1,C(F)(F)(F)S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F,157.193,-0.3274,27.27,280.147,1.0593,82.38
1,[(ETO)2IM][Tf2N]-CO2,313.35,25.7,0.396,22.970289,Synthetic (Bubble Point) Method,CCOn1cc[n+](OCC)c1,C(F)(F)(F)S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F,157.193,-0.3274,27.27,280.147,1.0593,82.38
2,[(ETO)2IM][Tf2N]-CO2,324.15,31.2,0.396,27.622487,Synthetic (Bubble Point) Method,CCOn1cc[n+](OCC)c1,C(F)(F)(F)S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F,157.193,-0.3274,27.27,280.147,1.0593,82.38
3,[(ETO)2IM][Tf2N]-CO2,333.85,36.0,0.396,31.703425,Synthetic (Bubble Point) Method,CCOn1cc[n+](OCC)c1,C(F)(F)(F)S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F,157.193,-0.3274,27.27,280.147,1.0593,82.38
4,[(ETO)2IM][Tf2N]-CO2,343.65,41.1,0.396,36.044576,Synthetic (Bubble Point) Method,CCOn1cc[n+](OCC)c1,C(F)(F)(F)S(=O)(=O)[N-]S(=O)(=O)C(F)(F)F,157.193,-0.3274,27.27,280.147,1.0593,82.38

In [18]:
CO2_solubility_dataset.columns

Index(['IL-CO2 Systems', 'T /K', 'P /bar', 'Solubility (ref.)',
       'Fugacity /bar', 'Experimental Method', 'cat_smiles', 'ani_smiles',
       'cat_MW', 'cat_LogP', 'cat_TPSA', 'ani_MW', 'ani_LogP', 'ani_TPSA'],
      dtype='object')

In [19]:
CO2_solubility_dataset.to_csv('CO2_solubility_dataset.csv',index=False)